[chore]: Fix cspell (#12740)
Attempting to fix the following failure in CI due to cspell.

> Warning: Unknown word (queuebatch)
> exporter/exporterhelper/internal/queuebatch/metadata.yaml:1:7 Unknown
word (queuebatch)
> Files checked: 289, Issues found: 1 in 1 files.
> Error: 1 spelling issue found in 1 of the 289 files checked.